#remote_theme: beAuthentic/askclass-course-theme
theme: askclass-course-theme

title: "50 English Conversations"
description: >
  Learn conversational English through 50 simple lessons.

acc:
  date_format: "%b %d, %y"
  short_name: "ENG-50"
  color:
    theme: "#88aa00"
    bg: "#222"
  url: "https://eng50.nissi.app"
  categories:
    - education
  logo:
    image: "logo.svg"
    size: 70
    height: 70
    alt_image: "logo.svg"
    alt_size: 200
    sizes: [ 48, 96, 144, 192, 300, 512, 800, 1024 ]
  shortcuts:
    - name: Syllabus
      url: https://eng50.nissi.app/session/syllabus
      desc: Class syllabus
  meta:
    apple_icon: "logo-square-300.png"
    og_image: "logo-square-512.png"
    shortcut:
      favicon: "favicon.ico"
      type: "image/png"
      image: "logo-96.png"
    keywords: >
      education,
      learning,
      theology,
      psychology,
      christianity
  footer:
    - icon: "lightbulb"
      href: "/session/syllabus"
      text: "Syllabus"
    - icon: "favorite"
      href: "/common"
      text: "300 Common Words"
  font_families:
    - Teko
    - Open+Sans:ital,wght@0,300;0,400;0,500;0,700;1,400;1,700
    - Josefin+Sans
    - Share+Tech+Mono
    - Lexend
    - Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200

collections_dir: content
collections:
  session:
    output: true
  segment:
    output: true
  common:
    output: true

defaults:
  - scope:
      path: "*.html"
    values:
      layout: "default"
  - scope:
      type: "session"
    values:
      layout: "session"
  - scope:
      type: "segment"
    values:
      layout: "segment"
  - scope:
      type: "common"
    values:
      layout: "common"

exclude:
  - CNAME
  - runme.sh
